runtime: python312
entrypoint: gunicorn -b :$PORT run:app

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'demo-secret-key-change-in-production'
  STATIC_URL_PREFIX: 'https://storage.googleapis.com/eplan-static-files'

handlers:
# CSS 파일은 GAE에서 직접 서빙
- url: /static/css
  static_dir: app/static/css
  secure: always
  expiration: "1d"

# JS 파일은 GAE에서 직접 서빙
- url: /static/js
  static_dir: app/static/js
  secure: always
  expiration: "1d"

# 나머지 모든 요청은 Flask 앱으로
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0  # 비용 절감: 사용 안 할 때 인스턴스 종료
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
